// Generated by gencpp from file mycar/speed.msg
// DO NOT EDIT!


#ifndef MYCAR_MESSAGE_SPEED_H
#define MYCAR_MESSAGE_SPEED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mycar
{
template <class ContainerAllocator>
struct speed_
{
  typedef speed_<ContainerAllocator> Type;

  speed_()
    : vx(0.0)
    , vy(0.0)
    , w(0.0)  {
    }
  speed_(const ContainerAllocator& _alloc)
    : vx(0.0)
    , vy(0.0)
    , w(0.0)  {
  (void)_alloc;
    }



   typedef float _vx_type;
  _vx_type vx;

   typedef float _vy_type;
  _vy_type vy;

   typedef float _w_type;
  _w_type w;





  typedef boost::shared_ptr< ::mycar::speed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mycar::speed_<ContainerAllocator> const> ConstPtr;

}; // struct speed_

typedef ::mycar::speed_<std::allocator<void> > speed;

typedef boost::shared_ptr< ::mycar::speed > speedPtr;
typedef boost::shared_ptr< ::mycar::speed const> speedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mycar::speed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mycar::speed_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mycar::speed_<ContainerAllocator1> & lhs, const ::mycar::speed_<ContainerAllocator2> & rhs)
{
  return lhs.vx == rhs.vx &&
    lhs.vy == rhs.vy &&
    lhs.w == rhs.w;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mycar::speed_<ContainerAllocator1> & lhs, const ::mycar::speed_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mycar

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mycar::speed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mycar::speed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mycar::speed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mycar::speed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mycar::speed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mycar::speed_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mycar::speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f3691ef5f5de1a108d3f9cc106129c39";
  }

  static const char* value(const ::mycar::speed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf3691ef5f5de1a10ULL;
  static const uint64_t static_value2 = 0x8d3f9cc106129c39ULL;
};

template<class ContainerAllocator>
struct DataType< ::mycar::speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mycar/speed";
  }

  static const char* value(const ::mycar::speed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mycar::speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 vx\n"
"float32 vy\n"
"float32 w\n"
;
  }

  static const char* value(const ::mycar::speed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mycar::speed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vx);
      stream.next(m.vy);
      stream.next(m.w);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct speed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mycar::speed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mycar::speed_<ContainerAllocator>& v)
  {
    s << indent << "vx: ";
    Printer<float>::stream(s, indent + "  ", v.vx);
    s << indent << "vy: ";
    Printer<float>::stream(s, indent + "  ", v.vy);
    s << indent << "w: ";
    Printer<float>::stream(s, indent + "  ", v.w);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MYCAR_MESSAGE_SPEED_H
